
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aevan
 */
public class BruteforceAttack extends javax.swing.JFrame {

    private String hash;
    
    /**
     * Creates new form PasswordCracker
     */
    public BruteforceAttack() {
        super("Bruteforce Attack Demo");
        initComponents();
        
        do{
            try{
                String input = JOptionPane.showInputDialog(rootPane, "Input a test password", "Password", JOptionPane.PLAIN_MESSAGE);
                
                this.hash = Hashing.getMd5(input.toUpperCase());
            }
            catch(Exception e){
                System.out.println("exception");
                continue;
            }
            
        }
        while(this.hash == null);
        
        hashLbl.setText(hash);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        md5HashLbl = new javax.swing.JLabel();
        hashLbl = new javax.swing.JLabel();
        crackBtn = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayArea.setColumns(20);
        displayArea.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        displayArea.setRows(5);
        jScrollPane1.setViewportView(displayArea);
        displayArea.setLineWrap(true);

        displayArea.setEditable(false);

        md5HashLbl.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        md5HashLbl.setText("MD5 Hash:");

        hashLbl.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        hashLbl.setText("hashLbl");

        crackBtn.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        crackBtn.setText("CRACK");
        crackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crackBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(md5HashLbl)
                        .addGap(18, 18, 18)
                        .addComponent(hashLbl)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md5HashLbl)
                    .addComponent(hashLbl))
                .addGap(18, 18, 18)
                .addComponent(crackBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crackBtnActionPerformed
        getPlain(hash);
    }//GEN-LAST:event_crackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BruteforceAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BruteforceAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BruteforceAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BruteforceAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BruteforceAttack().setVisible(true);
            }
        });
    }
    
    
    //User defined methods
    
    public String getPlain(String md5){
        String bruteforce;
        
        int[] array;
        StringBuilder permute = new StringBuilder(" ");
        Base26 num = new Base26();
        String lines = new String("MD5 HASH\tPLAINTEXT\n");
        do{
            
            array = num.toIntArray();
            for (int i = 0; i < array.length; i++) {
                permute.setCharAt(i, Hashing.ALPHABET.charAt(array[i]));
            }
            bruteforce = Hashing.getMd5(permute.toString());
            lines += (String.format("%s\t%s\n",bruteforce,permute.toString()));
            System.out.printf("%s\t%s\n",bruteforce,permute.toString());
            num.increment();
            
            if(num.length() > permute.length()){
                permute.append(" ");
            }
        }
        while(!bruteforce.equals(md5));
        displayArea.setText("");
        displayArea.append(lines);
        JOptionPane.showMessageDialog(rootPane, 
                String.format("The plain text of %s\nis: %s",
                        md5, permute.toString()),
                        "Done!", 
                        JOptionPane.INFORMATION_MESSAGE);
        return permute.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crackBtn;
    private javax.swing.JTextArea displayArea;
    private javax.swing.JLabel hashLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel md5HashLbl;
    // End of variables declaration//GEN-END:variables
}
