import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.lang.StringBuilder;
import java.util.ArrayList;

public class Hashing {
    static final String ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    static final int n = 26;
    public static String getMd5(String input){
        try{
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            
            BigInteger no = new BigInteger(1, messageDigest);
            
            String hashtext = no.toString(16);
            while(hashtext.length() < 32){
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }
        catch(NoSuchAlgorithmException e){
            throw new RuntimeException(e);
        }
    }
    
    public static void main(String args[]) throws NoSuchAlgorithmException{
        String password = "PUT";
        String hash = getMd5(password);
        String bruteforce;
        System.out.println("Your HashCode Generated by MD5 is: " + hash);
        int max = 3;
        int az = 26;
        int[] array;
        StringBuilder permute = new StringBuilder("   ");
        Base26 num = new Base26();
        do{
            array = num.toIntArray();
            for (int i = 0; i < array.length; i++) {
                permute.setCharAt(i, ALPHABET.charAt(array[i]));
                
            }
            bruteforce = getMd5(permute.toString());
            System.out.println(permute+"\t"+bruteforce);
            num.increment();
        }
        while(!bruteforce.equals(hash));
    }
    
    
    
}
