
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.ArrayList;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aevan
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Instance variables
     */
    private final ArrayList<JLabel> valuesLbl;
    private final ArrayList<Integer> values;
    
    //GridBagConstraints for values panel
    private GridBagConstraints valuesGBC;
    
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        super("Sorting Algorithms");
        valuesLbl = new ArrayList<>();
        values = new ArrayList<>();
        
        valuesGBC = new GridBagConstraints();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        algoPane = new javax.swing.JTabbedPane();
        selectionPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cmdPane = new javax.swing.JTextArea();
        insertionPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        mergePane = new javax.swing.JPanel();
        bubblePane = new javax.swing.JPanel();
        inputLbl = new javax.swing.JLabel();
        inputFld = new javax.swing.JTextField();
        insertBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        valuesScroll = new javax.swing.JScrollPane();
        valuesPane = new javax.swing.JPanel();
        sortBtn = new javax.swing.JButton();
        aboutBar = new javax.swing.JMenuBar();
        aboutItem = new javax.swing.JMenu();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdPane.setColumns(20);
        cmdPane.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        cmdPane.setRows(5);
        jScrollPane3.setViewportView(cmdPane);
        cmdPane.setLineWrap(true);
        cmdPane.setEditable(true);

        javax.swing.GroupLayout selectionPaneLayout = new javax.swing.GroupLayout(selectionPane);
        selectionPane.setLayout(selectionPaneLayout);
        selectionPaneLayout.setHorizontalGroup(
            selectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );
        selectionPaneLayout.setVerticalGroup(
            selectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
        );

        algoPane.addTab("Selection Sort", selectionPane);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);
        jTextArea1.setLineWrap(true);
        jTextArea1.setEditable(false);

        javax.swing.GroupLayout insertionPaneLayout = new javax.swing.GroupLayout(insertionPane);
        insertionPane.setLayout(insertionPaneLayout);
        insertionPaneLayout.setHorizontalGroup(
            insertionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertionPaneLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        insertionPaneLayout.setVerticalGroup(
            insertionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertionPaneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        algoPane.addTab("Insertion Sort", insertionPane);

        javax.swing.GroupLayout mergePaneLayout = new javax.swing.GroupLayout(mergePane);
        mergePane.setLayout(mergePaneLayout);
        mergePaneLayout.setHorizontalGroup(
            mergePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        mergePaneLayout.setVerticalGroup(
            mergePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        algoPane.addTab("Merge Sort", mergePane);

        javax.swing.GroupLayout bubblePaneLayout = new javax.swing.GroupLayout(bubblePane);
        bubblePane.setLayout(bubblePaneLayout);
        bubblePaneLayout.setHorizontalGroup(
            bubblePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        bubblePaneLayout.setVerticalGroup(
            bubblePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        algoPane.addTab("Bubble Sort", bubblePane);

        inputLbl.setText("Input:");

        insertBtn.setText("INSERT");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        valuesPane.setLayout(new java.awt.GridBagLayout());
        valuesScroll.setViewportView(valuesPane);

        sortBtn.setText("SORT");
        sortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBtnActionPerformed(evt);
            }
        });

        aboutItem.setText("About");
        aboutBar.add(aboutItem);

        setJMenuBar(aboutBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(inputLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertBtn)
                .addGap(18, 18, 18)
                .addComponent(clearBtn)
                .addGap(18, 18, 18)
                .addComponent(sortBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(valuesScroll)
            .addGroup(layout.createSequentialGroup()
                .addComponent(algoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLbl)
                    .addComponent(inputFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertBtn)
                    .addComponent(clearBtn)
                    .addComponent(sortBtn))
                .addGap(18, 18, 18)
                .addComponent(valuesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(algoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        valuesGBC.gridy=0;
        valuesGBC.gridx=0;
        valuesPane.removeAll();
        cmdPane.setText("");
        valuesPane.setLayout(new java.awt.GridBagLayout());
        valuesPane.revalidate();
        valuesPane.repaint();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        Integer newValue = Integer.parseInt(inputFld.getText());
        JLabel newLbl = new JLabel(newValue.toString());
        values.add(newValue);
        inputFld.setText("");
        
        System.out.println("Grid X: " + valuesGBC.gridx);
        insertValue(newLbl, valuesPane, valuesGBC);
        valuesPane.revalidate();
        valuesPane.repaint();
    }//GEN-LAST:event_insertBtnActionPerformed

    private void sortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed
        if(selectionPane.equals(algoPane.getComponent(algoPane.getSelectedIndex()))){
            cmdPane.setText("");
            int i;
            int j;
            int temp;
            int num = values.size();
            int array[] = new int[num];
            String line = "";
            for (i = 0; i < num; i++) {
                array[i] = values.get(i);
            }

            for (i = 0; i < (num - 1); i++) {
                for (j = 0; j < num - i - 1; j++) {
                    if (array[j] > array[j + 1]) {
                        temp = array[j];
                        array[j] = array[j + 1];
                        array[j + 1] = temp;
                    }
                }

                for (int l = 0; l < num; l++) {
                    line += " " + array[l];
                }
                line+="\n";
                cmdPane.append(line);
            }

            System.out.println("Sorted list of integers:");

            for (i = 0; i < num; i++)
                System.out.println(array[i]);
            }
        
    }//GEN-LAST:event_sortBtnActionPerformed

    /**
     * @param label the label to be added to the container
     * @param container the container that will receive the label
     * @param gbc the constraints for GridBagLayout
     */
    public static void insertValue(JLabel label, Container container, GridBagConstraints gbc){
        
        gbc.insets = new Insets(5,5,5,5);
        
        gbc.gridx++;
        if(gbc.gridx % 10 == 0){
            gbc.gridx = 0;
            gbc.gridy++;
        }
        
        container.add(label,gbc);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar aboutBar;
    private javax.swing.JMenu aboutItem;
    private javax.swing.JTabbedPane algoPane;
    private javax.swing.JPanel bubblePane;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextArea cmdPane;
    private javax.swing.JTextField inputFld;
    private javax.swing.JLabel inputLbl;
    private javax.swing.JButton insertBtn;
    private javax.swing.JPanel insertionPane;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mergePane;
    private javax.swing.JPanel selectionPane;
    private javax.swing.JButton sortBtn;
    private javax.swing.JPanel valuesPane;
    private javax.swing.JScrollPane valuesScroll;
    // End of variables declaration//GEN-END:variables
}
